CONFIG_APIC=y

CONFIG_XEN=y
CONFIG_XEN_BUS=y
CONFIG_PCI=y
CONFIG_PCI_EXPRESS_GENERIC_BRIDGE=y
CONFIG_VIRTIO=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_BLK=y
CONFIG_VIRTIO_SERIAL=y
CONFIG_VIRTIO_GPU=y

# FIXME: These shouldn't be needed.
CONFIG_IOAPIC=y
CONFIG_ACPI=y
CONFIG_MC146818RTC=y
