/*
 * Virtio TEE DLM (Debug Log Message) module
 *
 * Copyright 2023 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * Author: Jeshwanth Kumar <jeshwanthkumar.nk@amd.com>
 * Author: Rijo Thomas <Rijo-john.Thomas@amd.com>
 *
 */

#ifndef DLM_API_H
#define DLM_API_H
#include "virtio-tee-client.h"

#define TOKEN_FILE          "/data/debug_token.bin"
#define SIGNED_TOKEN_FILE   "/data/signed_debug_token.bin"

#define INVALID_DLM_SID     (0)
#define INFINITE_COUNT      (-1)

// Minimum Time interval between each AMDTEE_FetchDebugStrings call
#define SLEEP_INTERVAL_SEC  (0)
#define SLEEP_INTERVAL_NSEC (4000000L)    // Total interval : 0.004 seconds

/**
 * dlm_get_debug_token - Gets the debug token from Trusted OS and writes to
 * TOKEN_FILE (see above).
 *
 * @param fd    The file descripter of the opened TEE device.
 *
 * @return TEEC_SUCCESS         Get debug token was successful.
 * @return TEEC_Result          Something failed.
 */
TEEC_Result dlm_get_debug_token(int fd);

/**
 * dlm_start_session - Start debug session with TA.
 * Pre-requisite :  1. The TA should be already loaded and running in TEE.
 *                  2. The TOKEN_FILE generated by calling dlm_get_debug_token
 *                     should be signed using the same key that was used for
 *                     signing the TA. The signed debug token should be saved
 *                     as a SIGNED_TOKEN_FILE (see above for name and
 *                     location).
 * On success, this method spawns a separate thread to fetch debug logs from TA.
 * It will fetch debug log messages from TA in an infinite loop until the
 * dlm_stop_session get called.
 *
 * @param dlm_ctx   The initialized DLM context structure in which scope to
 *      start DLM session.
 * @param ta        The TA UUID for which the client application wants to
 *      start DLM session.
 *
 * @return TEEC_SUCCESS     Debug session started with TA successfully.
 * @return TEEC_Result      Something failed.
 */
TEEC_Result dlm_start_session(DLM_Context *dlm_ctx, const uint8_t *ta);


/**
 * dlm_stop_session - Stops DLM session and fetching of debug messages from TA.
 * For every DLM_StartSession, this method MUST be called for proper cleanup
 * up of resources allocated for the DLM session.
 *
 * @param dlm_ctx       The initialized DLM context structure in which scope to
 *                      stop DLM session.
 *
 * @return      None
 */
void dlm_stop_session(DLM_Context *dlm_ctx);
#endif
